#!/bin/bash

if [[ $EUID != 0 ]]; then
  echo "only root should run this script"
  exit 1
fi

USER=hsp

# enable wheel sudo access
visudo

# make user
useradd -m -g users -G wheel,adm,systemd-journal -s /bin/bash $USER
passwd $USER 

# Pretty fonts
echo \[infinality-bundle\] >> /etc/pacman.conf
echo Server = http://bohoomil.com/repo/\$arch >> /etc/pacman.conf
echo \[infinality-bundle-fonts\] >> /etc/pacman.conf
echo Server = http://bohoomil.com/repo/fonts >> /etc/pacman.conf

pacman-key -r 962DDE58
pacman-key --lsign-key 962DDE58
pacman -Syy
pacman -S infinality-bundle
pacman -S ibfonts-meta-base ibfonts-meta-extended ttf-nanum-fonts-ib ttf-nanumgothic-coding-ibx

# LAPTOP touchpad
pacman -S xf86-input-synaptics

# audio
pacman -S pulseaudio alsa-utils pulseaudio-alsa pavucontrol

# Intel video
pacman -S xf86-video-intel mesa mesa-libgl libva-intel-driver

# Nvidia video
pacman -S nvidia libvdpau libva-vdpau-driver

# X
pacman -S xorg-server xorg-xinit xorg-xsetroot xorg-setxkbmap xorg-xprop arandr

# Fonts
pacman -S ttf-dejavu ttf-symbola ttf-indixc-otf gnome-font-viewer xorg-xfontsel
pacman -S gnome-icon-theme lxappearance gnome-themes-standard numix-themes

# weird font error
cd /usr/share/fonts/local;mkfontdir

# useful
pacman -S tmux weechat htop zsh zsh-completions ranger gdisk dosfstools ntfs-3g bzr libgnomeui

# arch
pacman -S pkgfile expac abs

# media
pacman -S mpv feh mpd ncmpcpp mpc livestreamer

# devel
pacman -S vim git ruby python python2 nodejs openssh mongodb python-pip python2-pip lua luajit julia valgrind gdb svn

# change bash to zsh
chsh $USER

# wm
pacman -S chromium nautilus gvfs gvfs-mtp udisk2 wmname libnotify transmission-cli lm_sensors

# system
echo tmpfs       /home/$USER/.cache          tmpfs       uid=hsp,gid=users,nodev,nosuid,mode=755 0 0 >> /etc/fstab
echo tmpfs       /home/$USER/.compose-cache  tmpfs       uid=hsp,gid=users,nodev,nosuid,mode=755 0 0 >> /etc/fstab
echo tmpfs       /home/$USER/downloads       tmpfs       uid=hsp,gid=users,nodev,nosuid,mode=755 0 0 >> /etc/fstab

echo noarp >> /etc/dhcpcd.conf
