#!/bin/bash

# AUR
curl https://aur.archlinux.org/packages/co/cower/PKGBUILD > PKGBUILD
makepkg -sic
cower -d pacaur
cd pacaur
makepkg -sic

# extra
pacaur -y dunst-git compton-git gtk-theme-elementary-bzr source-code-pro-fonts sublime-text-dev firefox-nightly termite-git ponymix-git

# dotfiles
cd
git clone https://github.com/hspasta/dotfiles.git
cd dotfiles
./deploy

# vim
git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
vim +BundleInstall +qall
mkdir $HOME/.vim/{backup,swap}

# mpd
mkdir $HOME/.config/mpd
cp /usr/share/doc/mpd/mpdconf.example ~/.config/mpd/mpd.conf
mkdir ~/.config/mpd/playlists
touch ~/.config/mpd/{database,log,pid,state,sticker.sql}

