#!/bin/bash

# Meant to be run as initial login as user

if [[ $EUID == 0 ]]; then
  echo "root should NOT run this script"
  exit 1
fi

# pacaur
cower -d pacaur
cd pacaur
makepkg -sic

# arch
pacaur -y pkgbuild-introspection-git

# bspwm
# pacaur -y bspwm-git sxhkd-git sutils-git xtitle-git txtw-git sres-git
pacaur -y dmenu2 numix-circle-icon-theme-git dzen2-git otf-powerline-symbols-git

# i3
pa -y i3-git i3pystatus-git

# extra
pacaur -y dunst-git compton-git ponymix-git chromium-pepper-flash chromium-libpdf termite-git

# java and stuff
pacaur -y jdk android-udev

# laptop
pacaur -y simpfand-git

# dotfiles
cd
git clone https://github.com/hspasta/dotfiles.git
cd dotfiles
./deploy

# vim
mkdir $HOME/.vim/{backup,swap}
git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
vim +BundleInstall +qall
cd $HOME/.vim/bundle/tern_for_vim
npm install

# mpd
# mkdir -p $HOME/.config/mpd
# cp /usr/share/doc/mpd/mpdconf.example ~/.config/mpd/mpd.conf
# mkdir -p ~/.config/mpd/playlists
# touch ~/.config/mpd/{database,log,pid,state,sticker.sql}

# useful nodejs things I like
# sudo npm -g install yo generator-angular jshint grunt-cli bower

# arch
sudo pkgfile -u
sudo abs
