#!/bin/bash
#
# Meant to be from a LiveCD/USB/etc.
# Assuptions:
# - GPT only
# - Intel/AMD CPU
# - Wireless required
# - Neovim

MNT=/mnt

arch_chroot() {
  arch-chroot "$MNT" /bin/bash -c "${1}"
}

if [[ $EUID != 0 ]]; then
  printf "only root should run this script\n"
  exit 1
fi

read -ep "Which drive to install root (e.g /dev/sda): " drive
read -ep "Enter hostname: " hostname
read -ep "Enter username: " username
read -ep "Intel CPU (y/n): " intel

microcode=intel-ucode
[[ "$intel" != "y" ]] && microcode=amd-ucode

# ------ disk stuff ------
lsblk

# completely reset the drive
sgdisk --zap-all $drive

# clear partition data
sgdisk -o $drive

# Creates 2 paritions:
# 1. 256MB for GPT boot parition on FAT32
# 2. Everything else on EXT4
sgdisk -n 1:2048:526336 -n 2:528384:$(sgdisk -E $drive) -t 1:EF00 -t 2:8300 $drive
boot_part="${drive}1"
root_part="${drive}2"
sgdisk -p $drive
mkfs.ext4 -F "$root_part"
mount "$root_part" "$MNT"
mkdir "$MNT"/boot
mkfs.vfat -F32 $boot_part
mount "$boot_part" "$MNT"/boot

# ------ package installation ------
vim /etc/pacman.d/mirrorlist
pacstrap "$MNT" linux "$microcode" base base-devel sudo pkgfile ripgrep fd rsync htop

# ------ setting installation ------
# tmpfs   /home/$username/.cache    tmpfs  rw,size=6G,nodev,nosuid,uid=hsp,gid=users,mode=1700 0 0
genfstab -t PARTUUID "$MNT" >> "$MNT"/etc/fstab

# timezone
arch_chroot "ln -sf /usr/share/zoneinfo/America/Los_Angeles /etc/localtime"

# hostname
arch_chroot "hostnamectl set-hostname $hostname"

# locale stuff
arch_chroot "localectl set-locale LANG=en_US.UTF-8"
echo "en_US.UTF-8 UTF-8" >> "$MNT"/etc/locale.gen
arch_chroot "locale-gen"

# set bootloader
arch_chroot "bootctl --path=/boot install"

touch "$MNT"/boot/loader/entries/arch.conf
echo title   Arch Linux >> "$MNT"/boot/loader/entries/arch.conf
echo linux   /vmlinuz-linux >> "$MNT"/boot/loader/entries/arch.conf
echo initrd  "/${microcode}.img" >> "$MNT"/boot/loader/entries/arch.conf
echo initrd  /initramfs-linux.img >> "$MNT"/boot/loader/entries/arch.conf
echo options root=PARTUUID=$(lsblk -dno PARTUUID $root_part) rw quiet >> "$MNT"/boot/loader/entries/arch.conf

# ------ finishing installation ------
vi "$MNT"/etc/fstab
vi "$MNT"/etc/makepkg.conf

# MODULES=(i915 sd_mod ahci ext4)
# MODULES=(i915 nvme ext4)
# BINARIES=(fsck fsck.ext4)
# FILES=()
# HOOKS=(systemd)
# COMPRESSION="lz4"
# COMPRESSION_OPTIONS=(-1)
vi "$MNT"/etc/mkinitcpio.conf
arch_chroot "mkinitcpio -p linux"

arch_chroot "EDITOR=nvim visudo"
echo "Enter a password for root"
arch_chroot "passwd"

# ------ user creation ------
echo "Creating user $username..."
arch_chroot "useradd -m -g users -G wheel,adm,systemd-journal -s /usr/bin/zsh $username"
echo "Enter a password for $username"
arch_chroot "passwd $username"

# ------ install, unmount and finish! ------
# arch_chroot "systemctl enable gdm NetworkManager"

# Probably want to enable this on an SSD
# arch_chroot "systemctl enable fstrim.timer"

umount -R "$MNT"
cat << EOF

"All done! reboot into disk. (systemctl reboot)"

EOF

# intel thing to keep track
# dev.i915.perf_stream_paranoid=0
