#!/bin/bash


# disk stuff
lsblk
DRIVE=read -p "which drive to gdisk? (/dev/sd*)"
gdisk $DRIVE

# efi code = ef00
# efi partition size = 512M
# efi mount to /boot

#mkfs.vfat -F32 /dev/sd**
#mfks.*

#mount root and boot

# install base
pacstrap /mnt base base-devel gummiboot git iw wpa_supplicant dialog

# mount 
arch-chroot /mnt

# symlink from /usr/share/zoneinfo/* to /etc/localtime

# locale stuff
echo en_US.ISO-8859-1 >> /etc/locale.gen
echo ko_KR.UTF-8 UTF-8 >> /etc/locale.gen
locale-gen

# create locale.conf
echo LANG="en_US.UTF-8" > /etc/locale.conf
echo LC_COLLATE="C" >> /etc/locale.conf
echo LC_TIME="en_US.UTF-8" >> /etc/locale.conf

# edit mkinitcpio
vi /etc/mkinitcpio.conf
mkinitcpio -p linux

# edit settings
vi /etc/fstab

# set bootloader
gummiboot install
# it will probably fail to create the entry
# Ex:
touch /boot/loader/entries/arch.conf
echo title   Arch Linux >> /boot/loader/entries/arch.conf
echo linux   /vmlinuz-linux >> /boot/loader/entries/arch.conf
echo initrd  /initramfs-linux.img >> /boot/loader/entries/arch.conf
echo options root=/dev/sd## rw >> /boot/loader/entries/arch.conf

# set passwd
passwd

echo "You're done! reboot into disk. (systemctl reboot)"


