#!/bin/bash

# Pretty fonts
echo \[infinality-bundle\] >> /etc/pacman.conf
echo Server = http://ibn.net63.net/infinality-bundle/\$arch >> /etc/pacman.conf
pacman-key -r 962DDE58
pacman-key --lsign-key 962DDE58
pacman -Syy
pacman -S freetype2-infinality-ultimate fontconfig-infinality-ultimate cairo-infinality-ultimate

# LAPTOP touchpad
pacman -S xf86-input-synaptics

# audio
pacman -S pulseaudio alsa-utils pulseaudio-alsa pavucontrol

# Intel video
pacman -S xf86-video-intel mesa mesa-libgl libva-intel-driver

# Nvidia video
pacman -S nvidia libvdpau libva-vdpau-driver

# X
pacman -S xorg-server xorg-xinit xorg-xsetroot xorg-setxkbmap

# Fonts
pacman -S ttf-dejavu terminus-font ttf-symbola ttf-indixc-otf
pacman -S gnome-icon-theme elementary-icon-theme lxappearance gnome-themes-standard

# weird font error
cd /usr/share/fonts/local;mkfontdir

# useful
pacman -S tmux weechat htop zsh zsh-completions ranger gdisk dosfstools ntfs-3g bzr libgnomeui 

# arch
pacman -S pkgfile expac abs 

# media
pacman -S mpv feh 

# devel
pacman -S vim git ruby python python2 nodejs openssh mongodb python-pip python2-pip

# change bash to zsh
chsh hsp

# wm
pacman -S i3 dmenu chromium nautilus wmname libnotify dunst

