#!/bin/bash
#
# Meant to be run from Arch install

sudo pacman -S \
  go git mpv ranger curl \
  gnome gdm neovim python-neovim noto-fonts noto-fonts-emoji gnome-tweaks  \
  firefox ffirefox-i18n-ko irefox-i18n-en-us libu2f-host \
  iw iwd crda zsh

mkdir -p ~/tmp
cd ~/tmp
curl -O https://aur.archlinux.org/cgit/aur.git/snapshot/yay.tar.gz
tar xf yay.tar.gz
cd yay
makepkg -si
cd
rm -rf ~/tmp

mkdir -p ~/code/z
curl -o ~/code/z/z.sh https://raw.githubusercontent.com/rupa/z/master/z.sh
touch ~/.z

yay -S wl-clipboard-git ttf-google-fonts-git

git clone https://github.com/hspak/dotfiles.git
cd dotfiles
./setup
nvim +PlugInstall
