#!/bin/bash

if [[ $EUID == 0 ]]; then
  echo "root should NOT run this script"
  exit 1
fi

# AUR
curl https://aur.archlinux.org/packages/co/cower/PKGBUILD > PKGBUILD
makepkg -sic
cower -d pacaur
cd pacaur
makepkg -sic

# bspwm
pacaur -y bspwm-git sxhkd-git sutils-git xtitle-git dmenu2 numix-circle-icon-theme-git tamsynmod dzen2-git

# extra
pacaur -y dunst-git compton-git source-code-pro-fonts ponymix-git

# Korean fonts
pacaur -y ttf-alee ttf-nanum ttf-nanumgothic_coding ttf-unfonts-core

# dotfiles
cd
git clone https://github.com/hspasta/dotfiles.git
cd dotfiles
./deploy

# vim
mkdir $HOME/.vim/{backup,swap}
git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
vim +BundleInstall +qall

# mpd
mkdir $HOME/.config/mpd
cp /usr/share/doc/mpd/mpdconf.example ~/.config/mpd/mpd.conf
mkdir ~/.config/mpd/playlists
touch ~/.config/mpd/{database,log,pid,state,sticker.sql}

# need it for my notification scripts
sudo pacman -S python-dbus
sudo pip install notify2

# useful nodejs things I like
sudo npm -g install yo generator-angular jshint grunt-cli bower
