#!/bin/bash

# AUR
curl https://aur.archlinux.org/packages/co/cower/PKGBUILD > PKGBUILD
makepkg -sic
cower -d pacaur
cd pacaur
makepkg -sic

# extra
pacaur -y dunst-git compton-git gtk-theme-elementary-bzr source-code-pro-fonts sublime-text-dev chromium-libpdf chromium-pepper-flash termite-git

# dotfiles
cd
git clone https://github.com/hspasta/dotfiles.git
cd dotfiles
./deploy

# vim
git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
vim +BundleInstall +qall
mkdir $HOME/.vim/{backup,swap}

# system
echo tmpfs       $HOME/.cache          tmpfs       uid=hsp,gid=users,nodev,nosuid,mode=755 0 0 >> /etc/fstab
echo tmpfs       $HOME/.compose-cache  tmpfs       uid=hsp,gid=users,nodev,nosuid,mode=755 0 0 >> /etc/fstab
echo tmpfs       $HOME/downloads       tmpfs       uid=hsp,gid=users,nodev,nosuid,mode=755 0 0 >> /etc/fstab
