#!/bin/bash

# Meant to be run on the initial login as root

if [[ $EUID != 0 ]]; then
  echo "only root should run this script"
  exit 1
fi

USER=hsp

# enable wheel sudo access
visudo

# make user
useradd -m -g users -G wheel,adm,systemd-journal -s /bin/zsh $USER
passwd $USER

# Pretty fonts
echo \[infinality-bundle\] >> /etc/pacman.conf
echo Server = http://bohoomil.com/repo/\$arch >> /etc/pacman.conf
echo \[infinality-bundle-fonts\] >> /etc/pacman.conf
echo Server = http://bohoomil.com/repo/fonts >> /etc/pacman.conf

pacman-key -r 962DDE58
pacman-key --lsign-key 962DDE58
pacman -Syy
pacman -S infinality-bundle
pacman -S ibfonts-meta-base ibfonts-meta-extended ttf-nanum-fonts-ib ttf-nanumgothic-coding-ibx ttf-source-code-pro-ibx

# LAPTOP touchpad
pacman -S xf86-input-synaptics

# audio
pacman -S pulseaudio alsa-utils pulseaudio-alsa pavucontrol

# Intel video
pacman -S xf86-video-intel mesa mesa-libgl libva-intel-driver

# Nvidia video
pacman -S nvidia libvdpau libva-vdpau-driver nvidia-utils

# X
pacman -S xorg-server xorg-xinit xorg-xsetroot xorg-setxkbmap xorg-xprop arandr

# Fonts
pacman -S ttf-symbola ttf-indic-otf gnome-font-viewer xorg-xfontsel
pacman -S gnome-icon-theme lxappearance gnome-themes-standard numix-themes

# useful
pacman -S tmux weechat htop zsh-completions ranger gdisk dosfstools ntfs-3g bzr libgnomeui acpi lm_sensors qt iotop powertop avahi

# arch
pacman -S pkgfile expac abs burp pkgbuild-introspection-git

# media
pacman -S mpv feh mpd ncmpcpp mpc livestreamer libreoffice-common libreoffice-writer libreoffice-gnome libreoffice-en-US

# devel
pacman -S vim git ruby python python2 nodejs openssh mongodb python-pip python2-pip lua luajit julia valgrind gdb svn clang dnsutils traceroute

# wm
pacman -S chromium nautilus gvfs gvfs-mtp udisk2 wmname libnotify transmission-cli

# system
echo tmpfs       /home/$USER/.cache          tmpfs       uid=hsp,gid=users,nodev,nosuid,mode=755 0 0 >> /etc/fstab
echo tmpfs       /home/$USER/.compose-cache  tmpfs       uid=hsp,gid=users,nodev,nosuid,mode=755 0 0 >> /etc/fstab
echo tmpfs       /home/$USER/downloads       tmpfs       uid=hsp,gid=users,nodev,nosuid,mode=755 0 0 >> /etc/fstab

echo noarp >> /etc/dhcpcd.conf
vim /etc/makepkg.conf
