#!/bin/bash
#
# Meant to be run from Arch install

sudo pacman -S go git mpv ranger curl gnome-tweaks weechat firefox-i18n-ko

mkdir -p ~/tmp
cd ~/tmp
curl -O https://aur.archlinux.org/cgit/aur.git/snapshot/yay.tar.gz
tar xf yay.tar.gz
cd yay
makepkg -si
cd
rm -rf ~/tmp

mkdir -p ~/code/z
curl -o ~/code/z/z.sh https://raw.githubusercontent.com/rupa/z/master/z.sh

yay -S wl-clipboard-git ttf-google-fonts-git

git clone https://github.com/hspak/dotfiles.git
cd dotfiles
./setup
nvim +PlugInstall
