#!/bin/bash
#
# Meant to be from a LiveCD/USB/etc.

# I'm building a custom ISO from baseline which doesn't have all the nice things that the default Arsh ISO (releng) has:
# - gptfdisk             (need to update commands to use sfdisk instead)
# - dosfstools           (for mkfs.vfat - maybe something else can create the EFI boot drive now?)
# - arch-install-scripts (for pacstrap and genfstab)

set -e

MNT=/mnt

PUBKEY="ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGWDIH5VaGlCBgF8svMFxOXCg5WM8aBngYZXmksY1XR6"
MIRROR='Server = https://mirrors.xtom.com/archlinux/$repo/os/$arch'

arch_chroot() {
  arch-chroot "$MNT" /bin/bash -c "${1}"
}

if [[ $EUID != 0 ]]; then
  printf "only root should run this script\n"
  exit 1
fi

# ------ disk stuff ------
lsblk
read -ep "Which drive to install root (e.g /dev/sda): " drive

# completely reset the drive
sgdisk --zap-all $drive

# clear partition data
sgdisk -o $drive

# Creates 2 paritions:
# 1. 256MB for GPT boot parition on FAT32
# 2. Everything else on EXT4
sgdisk -n 1:2048:526336 -n 2:528384:$(sgdisk -E $drive) -t 1:EF00 -t 2:8300 $drive
boot_part="${drive}1"
root_part="${drive}2"
sgdisk -p $drive
mkfs.ext4 -F "$root_part"
mount "$root_part" "$MNT"
mkdir "$MNT"/boot
mkfs.vfat -F32 $boot_part
mount "$boot_part" "$MNT"/boot

# ------ package installation ------
echo "$MIRROR" >> /etc/pacman.d/mirrorlist

pacman-key --init
pacman-key --populate archlinux
pacstrap "$MNT" base linux linux-firmware intel-ucode sudo pkgfile ripgrep fd rsync htop neovim zsh bash

# ------ setting installation ------
genfstab -t PARTUUID "$MNT" >> "$MNT"/etc/fstab

# SSD setup
arch_chroot "systemctl enable fstrim.timer"

# time stuff
arch_chroot "ln -sf /usr/share/zoneinfo/America/Los_Angeles /etc/localtime"
arch_chroot "systemctl enable systemd-timesyncd.service"
arch_chroot "timedatectl set-ntp true"
arch_chroot "hwclock --systohc"

# hostname
arch_chroot "hostnamectl set-hostname box"

# locale stuff
echo "en_US.UTF-8 UTF-8" >> "$MNT"/etc/locale.gen
arch_chroot "localectl set-locale LANG=en_US.UTF-8"
arch_chroot "locale-gen"
echo "LANG=en_US.UTF-8" >> "$MNT"/etc/locale.conf

# set bootloader
arch_chroot "bootctl --path=/boot install"

touch "$MNT"/boot/loader/entries/arch.conf
echo title   Arch Linux >> "$MNT"/boot/loader/entries/arch.conf
echo linux   /vmlinuz-linux >> "$MNT"/boot/loader/entries/arch.conf
echo initrd  "/intel-ucode.img" >> "$MNT"/boot/loader/entries/arch.conf
echo initrd  /initramfs-linux.img >> "$MNT"/boot/loader/entries/arch.conf
echo options root=PARTUUID=$(lsblk -dno PARTUUID $root_part) rw quiet >> "$MNT"/boot/loader/entries/arch.conf

# setup systemd-resolved
arch_chroot "systemctl enable systemd-resolved"
ln -sf /run/systemd/resolve/stub-resolv.conf "$MNT"/etc/resolv.conf

# setup systemd-networkd
touch "$MNT"/etc/systemd/network/20-enp4s0.network
echo "[Match]" >> "$MNT"/etc/systemd/network/20-enp4s0.network
echo "Name=enp4s0" >> "$MNT"/etc/systemd/network/20-enp4s0.network
echo "[Network]" >> "$MNT"/etc/systemd/network/20-enp4s0.network
echo "DHCP=yes" >> "$MNT"/etc/systemd/network/20-enp4s0.network
arch_chroot "systemctl enable systemd-networkd"

# setup ssh
arch_chroot "mkdir /root/.ssh"
echo "$PUBKEY" >> "$MNT"/root/.ssh/authorized_keys
arch_chroot "chmod 0600 /root/.ssh/authorized_keys"
arch_chroot "systemctl enable sshd"

# ------ finishing installation ------
arch_chroot "mkinitcpio -p linux"

# ------ user management ------
arch_chroot "EDITOR=nvim visudo"
echo "Enter a password for root"
arch_chroot "passwd"

echo "Creating user hsp"
arch_chroot "useradd -m -g users -G wheel,adm,systemd-journal -s /usr/bin/zsh hsp"
echo "Enter a password for hsp"
arch_chroot "passwd hsp"

# ------ install, unmount and finish! ------
umount -R "$MNT"/boot
umount -R "$MNT"
cat << EOF

"All done! reboot into disk. (systemctl reboot)"

EOF
