#!/bin/bash
#
# Meant to be run from Arch install

# TODO:
# Some wifi network automation stuff

sudo pacman -Syy

sudo pacman -S \
  go mpv ranger curl \
  gnome python-neovim noto-fonts noto-fonts-emoji ttf-google-fonts-git gnome-tweaks  \
  firefox ffirefox-i18n-ko irefox-i18n-en-us libu2f-host \
  iw crda zsh

mkdir -p ~/tmp
cd ~/tmp
curl -O https://aur.archlinux.org/cgit/aur.git/snapshot/zur.tar.gz
tar xf zur.tar.gz
cd zur
makepkg -si
cd
rm -rf ~/tmp

mkdir -p ~/code/z
curl -o ~/code/z/z.sh https://raw.githubusercontent.com/rupa/z/master/z.sh
touch ~/.z

zur -S sway-git swayidle-git swaylock-git wlroots-git wl-clipboard-git \
  grim-git mako-git \
  brightnessztl i3status-rust-git ttf-font-awesome-4

git clone https://github.com/hspak/dotfiles.git
cd dotfiles
./setup
